"""added indexes OrderItems and Order

Revision ID: 0b2ccef1b8a7
Revises: 559dd66ff3f6
Create Date: 2026-02-06 09:17:11.737807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2ccef1b8a7'
down_revision: Union[str, Sequence[str], None] = '559dd66ff3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_orders_create_at', 'orders', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_create_at', table_name='orders')
    op.drop_index('ix_orders_items_order_id', table_name='order_items')
    # ### end Alembic commands ###
