"""added index idx_product_category_id Product

Revision ID: 3d68d3a6470d
Revises: 0b2ccef1b8a7
Create Date: 2026-02-06 09:25:49.866324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d68d3a6470d'
down_revision: Union[str, Sequence[str], None] = '0b2ccef1b8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_products_category_id', 'products', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products_category_id', table_name='products')
    # ### end Alembic commands ###
